- name: Grundkonfiguration für Debian-VMs
  hosts: all
  become: yes

  vars:
    common_packages:
      - sudo
      - vim
      - curl
      - htop
      - net-tools
      - gnupg

  tasks:
    - name: Hostname setzen
      ansible.builtin.hostname:
        name: "{{ inventory_hostname }}"

    - name: Pakete installieren
      ansible.builtin.apt:
        name: "{{ common_packages }}"
        state: present
        update_cache: yes

    - name: Zeitzone setzen
      community.general.timezone:
        name: Europe/Zurich